//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference ementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 10:02:08 AM EDT 
//


package one.jodi.core.model.visitors;

import one.jodi.core.model.*;

public class BaseVisitor
        implements Visitor {

    @Override
    public void visit(Dataset aBean) {

    }

    @Override
    public void visit(Datasets aBean) {

    }

    @Override
    public void visit(FlowType aBean) {

    }

    @Override
    public void visit(FlowsType aBean) {

    }

    @Override
    public void visit(KmOption aBean) {

    }

    @Override
    public void visit(KmOptions aBean) {

    }

    @Override
    public void visit(KmType aBean) {

    }

    @Override
    public void visit(Lookup aBean) {

    }

    @Override
    public void visit(Lookups aBean) {

    }

    @Override
    public void visit(MappingExpressions aBean) {

    }

    @Override
    public void visit(Mappings aBean) {

    }

    @Override
    public void visit(ColumnType aBean) {

    }

    @Override
    public void visit(PivotType aBean) {

    }

    @Override
    public void visit(Properties aBean) {

    }

    @Override
    public void visit(Source aBean) {

    }

    @Override
    public void visit(Targetcolumn aBean) {

    }

    @Override
    public void visit(Transformation aBean) {

    }

    @Override
    public void visit(UnPivotType aBean) {

    }

    @Override
    public void visit(MappingCommandType aBean) {

    }

    @Override
    public void visit(SubQueryType aBean) {

    }

    @Override
    public void visit(SyntheticRowType aBean) {

    }

}
