//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 10:02:08 AM EDT 
//


package one.jodi.core.model.visitors;

import one.jodi.core.model.*;

public interface Visitor {

    public void visit(Dataset aBean);

    public void visit(Datasets aBean);

    public void visit(FlowType aBean);

    public void visit(FlowsType aBean);

    public void visit(KmOption aBean);

    public void visit(KmOptions aBean);

    public void visit(KmType aBean);

    public void visit(Lookup aBean);

    public void visit(Lookups aBean);

    public void visit(MappingExpressions aBean);

    public void visit(Mappings aBean);

    public void visit(ColumnType aBean);

    public void visit(PivotType aBean);

    public void visit(Properties aBean);

    public void visit(Source aBean);

    public void visit(Targetcolumn aBean);

    public void visit(Transformation aBean);

    public void visit(UnPivotType aBean);

    public void visit(MappingCommandType aBean);

    public void visit(SubQueryType aBean);

    public void visit(SyntheticRowType aBean);

}
