export ORCL_SYS_USER="ADMIN"

sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql CHINOOK $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql DWH_CON $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql DWH_CON_CHINOOK $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql DWH_DMT $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql DWH_SRC $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql DWH_STG $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql DWH_STI $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql DWH_STO $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql REF $OCI_PWD DATA TEMP
