export ORCL_SYS_USER="ADMIN"

sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN1 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN2 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN3 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN4 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN5 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN6 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN7 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN8 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN9 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN10 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN11 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN12 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN13 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN14 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN15 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN16 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN17 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN18 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN19 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN20 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN21 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN22 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN23 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN24 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN25 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN26 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN27 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN28 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN29 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EXN30 $OCI_PWD DATA TEMP

sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG1 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG2 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG3 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG4 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG5 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG6 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG7 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG8 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG9 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG10 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG11 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG12 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG13 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG14 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG15 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG16 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG17 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG18 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG19 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG20 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG21 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG22 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG23 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG24 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG25 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG26 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG27 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG28 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG29 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql STG30 $OCI_PWD DATA TEMP

sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql ODITMP $OCI_PWD DATA TEMP

# sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql MTM $OCI_PWD DATA TEMP

sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql MCM $OCI_PWD DATA TEMP

sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql ERM $OCI_PWD DATA TEMP

sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql INF $OCI_PWD DATA TEMP

sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql MCV $OCI_PWD DATA TEMP

sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql DWHPUBLIC $OCI_PWD DATA TEMP

sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql EDW $OCI_PWD DATA TEMP

sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql SBX1 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql SBX2 $OCI_PWD DATA TEMP
sql $ORCL_SYS_USER/$OCI_ADMIN_PWD@$OCI_URL @create_user.sql SBX3 $OCI_PWD DATA TEMP
