//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 10:02:08 AM EDT 
//


package one.jodi.core.model.visitors;


public interface TraversingVisitorProgressMonitor {


    public void visited(Visitable aVisitable);

    public void traversed(Visitable aVisitable);

}
