drop INDEX "DWH_DMT"."W_INVOICELINE_F_I1" ;
drop INDEX "DWH_DMT"."W_INVOICELINE_F_I2";
drop INDEX "DWH_DMT"."W_INVOICELINE_F_I3" ;
drop INDEX "DWH_DMT"."W_INVOICELINE_F_I4";
drop INDEX "DWH_DMT"."W_INVOICELINE_F_I5"  ;

CREATE BITMAP INDEX "DWH_DMT"."W_INVOICELINE_F_I1" ON "DWH_DMT"."W_INVOICELINE_F" ("INVL_CUST_WID") local ;
CREATE BITMAP INDEX "DWH_DMT"."W_INVOICELINE_F_I2" ON "DWH_DMT"."W_INVOICELINE_F" ("INVL_SUPPORTREP_WID") local;
CREATE BITMAP INDEX "DWH_DMT"."W_INVOICELINE_F_I3" ON "DWH_DMT"."W_INVOICELINE_F" ("INVL_SUPERVISOR_WID") local ;
CREATE BITMAP INDEX "DWH_DMT"."W_INVOICELINE_F_I4" ON "DWH_DMT"."W_INVOICELINE_F" ("INVL_TRCK_WID") local;
CREATE BITMAP INDEX "DWH_DMT"."W_INVOICELINE_F_I5" ON "DWH_DMT"."W_INVOICELINE_F" ("INVL_ALBM_WID") local ;

truncate table dwh_dmt.w_invoiceline_f;
EXEC DBMS_STATS.GATHER_TABLE_STATS ('DWH_DMT', 'W_INVOICELINE_F');

exit