--
-- Uninstall
--

drop user DWH_CON_CHINOOK cascade;

drop user DWH_CON cascade;

drop user DWH_DMT cascade;

drop user DWH_OIL cascade;

drop user DWH_STO cascade;

drop user DWH_STI cascade;

-- 
-- Install 
--

CREATE USER "DWH_CON_CHINOOK" IDENTIFIED BY  DWH_CON_CHINOOK
  DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP"
/
  GRANT "CONNECT" TO "DWH_CON_CHINOOK"
/
  GRANT "RESOURCE" TO "DWH_CON_CHINOOK"
/
  GRANT ANALYZE ANY DICTIONARY TO "DWH_CON_CHINOOK"
/
  GRANT ANALYZE ANY TO "DWH_CON_CHINOOK"
/
  GRANT SELECT ANY SEQUENCE TO "DWH_CON_CHINOOK"
/
  GRANT CREATE ANY VIEW TO "DWH_CON_CHINOOK"
/
  GRANT DROP ANY INDEX TO "DWH_CON_CHINOOK"
/
  GRANT ALTER ANY INDEX TO "DWH_CON_CHINOOK"
/
  GRANT CREATE ANY INDEX TO "DWH_CON_CHINOOK"
/
  GRANT DELETE ANY TABLE TO "DWH_CON_CHINOOK"
/ 
  GRANT UPDATE ANY TABLE TO "DWH_CON_CHINOOK"
/
  GRANT INSERT ANY TABLE TO "DWH_CON_CHINOOK"
/
  GRANT SELECT ANY TABLE TO "DWH_CON_CHINOOK"
/
  GRANT COMMENT ANY TABLE TO "DWH_CON_CHINOOK"
/
  GRANT LOCK ANY TABLE TO "DWH_CON_CHINOOK"
/
  GRANT DROP ANY TABLE TO "DWH_CON_CHINOOK"
/
  GRANT ALTER ANY TABLE TO "DWH_CON_CHINOOK"
/
  GRANT CREATE ANY TABLE TO "DWH_CON_CHINOOK"
/
  GRANT UNLIMITED TABLESPACE TO "DWH_CON_CHINOOK"
/
  GRANT EXECUTE ON "SYS"."DBMS_STATS" TO "DWH_CON_CHINOOK"
/
  CREATE USER "DWH_CON" IDENTIFIED BY DWH_CON
    DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP"
/
  GRANT UNLIMITED TABLESPACE TO "DWH_CON"        
/ 
  CREATE USER "DWH_DMT" IDENTIFIED BY DWH_DMT
    DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP"
/
  GRANT UNLIMITED TABLESPACE TO "DWH_DMT"                               
/
  CREATE USER "DWH_OIL" IDENTIFIED BY DWH_OIL
    DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP"
/
  GRANT UNLIMITED TABLESPACE TO "DWH_OIL"                               
/
  CREATE USER "DWH_STO" IDENTIFIED BY DWH_STO 
    DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP"
/
  GRANT UNLIMITED TABLESPACE TO "DWH_STO"                               
/ 
  CREATE USER
    "DWH_STI" IDENTIFIED BY DWH_STI
    DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP"
/
GRANT UNLIMITED TABLESPACE TO "DWH_STI"
/
GRANT CREATE DATABASE LINK TO "DWH_CON_CHINOOK" 
/
GRANT CREATE ANY SYNONYM TO "DWH_CON_CHINOOK" 
/
exit