package one.jodi.base.service.bi;

import one.jodi.base.service.bi.ast.ExprNode;

import java.util.List;
import java.util.Optional;


/**
 * Represents the Ast generated by the Spoofax parser or the error codes and
 * messages in case of failure. This class is implemented by Spoofax module.
 */
public interface ParseResult {

    /**
     * @return AST describing the expression. If error occurred, Option.empty()
     * is returned
     */
    Optional<ExprNode> getAst();

    ;

    List<String> getErrorMessages();

    Optional<ErrorType> getErrorType();

    Optional<String> getInferredType();

    enum ErrorType {SYNTAX, COLUMN_NOT_FOUND}

}
